//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public Author()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int id { get; set; }
        public string author_name { get; set; }
        public string description { get; set; }
        public string birth_year { get; set; }
        public string status { get; set; }
        public string image { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
    }
}
