//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookstore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        public Book()
        {
            this.Order_Detail = new HashSet<Order_Detail>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public int price { get; set; }
        public int quantity_in_stock { get; set; }
        public int publisher_id { get; set; }
        public int category_id { get; set; }
        public int author_id { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> public_date { get; set; }
        public string edition { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
    }
}
