//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookstore.Models
{
    using bookstore.Areas.Admin.Controllers;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Category : BaseController
    {
        public Category()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int id { get; set; }
        public string category_name { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }

        public List<Book> findBookByCategory()
        {
            List<Book> listBook = db.Books.Where(b => b.category_id == id).ToList();
            return listBook;
        }
    }
}
