//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Order_Detail = new HashSet<Order_Detail>();
        }
    
        public int id { get; set; }
        public int order_item_id { get; set; }
        public int shipping_price { get; set; }
        public int user_id { get; set; }
        public string status { get; set; }
        public double total_price { get; set; }
        public int payment_id { get; set; }
    
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
        public virtual Payment_card Payment_card { get; set; }
        public virtual User User { get; set; }
    }
}
