//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_card
    {
        public Payment_card()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public int card_number { get; set; }
        public System.DateTime from_date { get; set; }
        public System.DateTime to_date { get; set; }
        public int user_id { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual User User { get; set; }
    }
}
